http:
  port: ${PORT:-3000}

apiEndpoints:
  order:
    host: "*"
    paths:
      - "/order"
      - "/order/:id"

  dish:
    host: "*"
    paths:
      - "/kitchen"
      - "/kitchen/:id"

  ingredient:
    host: "*"
    paths:
      - "/inventory"
      - "/inventory/:ingredient"

  purchase:
    host: "*"
    paths:
      - "/market"
      - "/market/:id"

serviceEndpoints:
  orderService:
    url: "${ORDER_SERVICE_URL:-http://localhost:3002/ms}"

  kitchenService:
    url: "${KITCHEN_SERVICE_URL:-http://localhost:3003/ms}"

  inventoryService:
    url: "${INVENTORY_SERVICE_URL:-http://localhost:3004/ms}"

  marketService:
    url: "${MARKET_SERVICE_URL:-http://localhost:3005/ms}"

policies:
  - cors
  - proxy

pipelines:
  orderPipeline:
    apiEndpoints:
      - order
    policies:
      - cors:
          - action:
              origin: "*"
              methods:
                - "GET"
                - "POST"
                - "OPTIONS"
              allowedHeaders:
                - "Content-Type"
                - "Authorization"
      - proxy:
          - action:
              serviceEndpoint: orderService

  dishPipeline:
    apiEndpoints:
      - dish
    policies:
      - cors:
          - action:
              origin: "*"
              methods:
                - "GET"
                - "OPTIONS"
              allowedHeaders:
                - "Content-Type"
                - "Authorization"
      - proxy:
          - action:
              serviceEndpoint: kitchenService

  ingredientPipeline:
    apiEndpoints:
      - ingredient
    policies:
      - cors:
          - action:
              origin: "*"
              methods:
                - "GET"
                - "OPTIONS"
              allowedHeaders:
                - "Content-Type"
                - "Authorization"
      - proxy:
          - action:
              serviceEndpoint: inventoryService

  purchaseHistoryPipeline:
    apiEndpoints:
      - purchase
    policies:
      - cors:
          - action:
              origin: "*"
              methods:
                - "GET"
                - "OPTIONS"
              allowedHeaders:
                - "Content-Type"
                - "Authorization"
      - proxy:
          - action:
              serviceEndpoint: marketService